version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: snap-hutao-open-graph-server:1.0
    container_name: Snap-Hutao-Open-Graph-Server
    ports:
      - "3965:8080"
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - tunnel

  tunnel:
    container_name: Snap-Hutao-Generic-API-Tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=YOUR_TUNNEL_TOKEN